apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: jhansisaketa/nba-rest
        env:
        - name: MINIO_HOST
          value: "minio:9000"
        - name: FLASK_PORT
          value: "5000"
