kind: Service
apiVersion: v1
metadata:
  name: "rabbitmq"
spec:
  type: LoadBalancer
  selector:
    app: "rabbitmq"
  ports:
    - protocol: "TCP"
      port: 5672
      targetPort: 5672
  


  