apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: jhansisaketa/data-collector
        env:
        - name: MINIO_HOST
          value: "minio:9000"
        - name: RABBIT_HOST
          value: rabbitmq
